### PR TITLE
Change of file organization and support 64-bit binary build

### PR DESCRIPTION
**Pull request by keenhenry**
Moved cgi scripts related files (cgi_custom.h and cgi_custom.c) into eserv library (lib/eserv) and remove 32-bit only binary build from Makefiles.

### CODE REVIEW

**Comment by tjjh89017** [comment]
Thanks for pull request.
I'll work on these changes on my developing branch "mwmodel"
Thanks a lot

**Comment by keenhenry** [comment]
Hi Date,

I saw there are several branches, including 'mwmodel'. What are those
branches for?

If you think appropriate, I will try to merge some important features/bug
fixes from those branches to master.

As for the master branch, I can think of two improvements:

- the server is not thread-safe. I plan to make it thread-safe. Have you
already implemented thread-safety in other branches? Or already have some
concrete ideas about how to do it?

- login/registration/session cgi seems not working properly I plan to
improve it.

Any other improvements on your mind?

Cheers,

On Thu, Jan 22, 2015 at 6:52 AM, Date Huang <notifications@github.com>
wrote:

> Thanks for pull request.
> I'll work on these changes on my developing branch "mwmodel"
> Thanks a lot
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tjjh89017/eserv/pull/3#issuecomment-70974932>.
>



-- 
Henry Huang

**Comment by tjjh89017** [comment]
Hi Henry,

`master` is the origin branch form jserv's repo with some simple change.
`mwmodel` is the branch using Libevent to improve the performance, and I can say it's the mainline develop branch.
Other branchs are testing for Libevent in the past. It's EOL now. I forgot to remove those branch.

I'm not sure that `mwmodel` is already thread-safe, but I have protected some shared variables by the mutex. I think the performance of `mwmodel` still has room for improvement.

About login/registration/session cgi, I still work on them, but I focus on ARM OS recently. I'll check for that in severval days.

I'll write some docs to explain.
Thanks for advice.

**Comment by keenhenry** [comment]
Hi Date,

Okay, now I understand. Thank you for your clear explanation.

I can help you to at least backport your mutex solutions to master branch,
and perhaps even to improve if I could.

Also, I think I will also try to implement the login/session functionality
on master branch, if you don't mind.

It's good to hear that you're focusing on ARM architecture now, because I
plan to use eServ on Raspberry PI and see how it works:)

I am excited to see how you are going to use libevent to replace current
callback mechanism. I am not experienced with using libevent, but if you
need help, please let me know, it would be interesting to learn.

And of course, the experiments I do will only be on my own fork first.

On Wed, Feb 4, 2015 at 6:12 AM, Date Huang notifications@github.com wrote:

> Hi Henry,
> 
> master is the origin branch form jserv's repo with some simple change.
> mwmodel is the branch using Libevent to improve the performance, and I
> can say it's the mainline develop branch.
> Other branchs are testing for Libevent in the past. It's EOL now. I forgot
> to remove those branch.
> 
> I'm not sure that mwmodel is already thread-safe, but I have protected
> some shared variables by the mutex. I think the performance of mwmodel
> still has room for improvement.
> 
> About login/registration/session cgi, I still work on them, but I focus on
> ARM OS recently. I'll check for that in severval days.
> 
> I'll write some docs to explain.
> Thanks for advice.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tjjh89017/eserv/pull/3#issuecomment-72791960.

## 

Henry Huang

**Comment by tjjh89017** [comment]
Just do it!!

**Comment by keenhenry** [comment]
Got it!

**Pull request merged**
